namespace Spa
{
    partial class frmCapacidadesYCupos
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle1 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle2 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle8 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle9 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle10 = new System.Windows.Forms.DataGridViewCellStyle();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(frmCapacidadesYCupos));
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle3 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle4 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle5 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle6 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle7 = new System.Windows.Forms.DataGridViewCellStyle();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges4 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges5 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges6 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            this.dgvCapacidades = new System.Windows.Forms.DataGridView();
            this.tableLayoutPanel1 = new System.Windows.Forms.TableLayoutPanel();
            this.dtpFechaCapacidades = new Bunifu.UI.WinForms.BunifuDatePicker();
            this.btnBuscarCapacidad = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnExportarCapacidadesExcel = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.dgvCupos = new System.Windows.Forms.DataGridView();
            this.cbServicio = new Bunifu.UI.WinForms.BunifuDropdown();
            this.dtpFechaCupos = new Bunifu.UI.WinForms.BunifuDatePicker();
            this.btnBuscarCupos = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.lblCupos = new System.Windows.Forms.Label();
            this.lblCapacidades = new System.Windows.Forms.Label();
            this.btnExportarCuposPDF = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnExportarCuposExcel = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnExportarCapacidadesPDF = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            ((System.ComponentModel.ISupportInitialize)(this.dgvCapacidades)).BeginInit();
            this.tableLayoutPanel1.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.dgvCupos)).BeginInit();
            this.SuspendLayout();
            // 
            // dgvCapacidades
            // 
            this.dgvCapacidades.AllowUserToAddRows = false;
            this.dgvCapacidades.AllowUserToDeleteRows = false;
            dataGridViewCellStyle1.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleCenter;
            dataGridViewCellStyle1.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(27)))), ((int)(((byte)(29)))), ((int)(((byte)(36)))));
            this.dgvCapacidades.AlternatingRowsDefaultCellStyle = dataGridViewCellStyle1;
            this.dgvCapacidades.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.Fill;
            this.dgvCapacidades.AutoSizeRowsMode = System.Windows.Forms.DataGridViewAutoSizeRowsMode.AllCells;
            this.dgvCapacidades.BackgroundColor = System.Drawing.Color.FromArgb(((int)(((byte)(31)))), ((int)(((byte)(33)))), ((int)(((byte)(37)))));
            this.dgvCapacidades.CellBorderStyle = System.Windows.Forms.DataGridViewCellBorderStyle.None;
            this.dgvCapacidades.ColumnHeadersBorderStyle = System.Windows.Forms.DataGridViewHeaderBorderStyle.None;
            dataGridViewCellStyle2.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleCenter;
            dataGridViewCellStyle2.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(126)))), ((int)(((byte)(249)))));
            dataGridViewCellStyle2.Font = new System.Drawing.Font("Microsoft Sans Serif", 11.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            dataGridViewCellStyle2.ForeColor = System.Drawing.Color.White;
            dataGridViewCellStyle2.SelectionBackColor = System.Drawing.SystemColors.HotTrack;
            dataGridViewCellStyle2.SelectionForeColor = System.Drawing.Color.White;
            dataGridViewCellStyle2.WrapMode = System.Windows.Forms.DataGridViewTriState.True;
            this.dgvCapacidades.ColumnHeadersDefaultCellStyle = dataGridViewCellStyle2;
            this.dgvCapacidades.ColumnHeadersHeight = 50;
            this.dgvCapacidades.ColumnHeadersHeightSizeMode = System.Windows.Forms.DataGridViewColumnHeadersHeightSizeMode.DisableResizing;
            this.tableLayoutPanel1.SetColumnSpan(this.dgvCapacidades, 3);
            dataGridViewCellStyle8.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleCenter;
            dataGridViewCellStyle8.BackColor = System.Drawing.Color.Black;
            dataGridViewCellStyle8.Font = new System.Drawing.Font("Comic Sans MS", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            dataGridViewCellStyle8.ForeColor = System.Drawing.Color.White;
            dataGridViewCellStyle8.SelectionBackColor = System.Drawing.SystemColors.GradientActiveCaption;
            dataGridViewCellStyle8.SelectionForeColor = System.Drawing.SystemColors.HighlightText;
            dataGridViewCellStyle8.WrapMode = System.Windows.Forms.DataGridViewTriState.False;
            this.dgvCapacidades.DefaultCellStyle = dataGridViewCellStyle8;
            this.dgvCapacidades.Dock = System.Windows.Forms.DockStyle.Fill;
            this.dgvCapacidades.EnableHeadersVisualStyles = false;
            this.dgvCapacidades.GridColor = System.Drawing.Color.SteelBlue;
            this.dgvCapacidades.Location = new System.Drawing.Point(3, 163);
            this.dgvCapacidades.Name = "dgvCapacidades";
            this.dgvCapacidades.ReadOnly = true;
            this.dgvCapacidades.RowHeadersBorderStyle = System.Windows.Forms.DataGridViewHeaderBorderStyle.None;
            dataGridViewCellStyle9.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleCenter;
            dataGridViewCellStyle9.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(39)))), ((int)(((byte)(41)))), ((int)(((byte)(61)))));
            dataGridViewCellStyle9.Font = new System.Drawing.Font("Comic Sans MS", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            dataGridViewCellStyle9.ForeColor = System.Drawing.Color.White;
            dataGridViewCellStyle9.SelectionBackColor = System.Drawing.SystemColors.Highlight;
            dataGridViewCellStyle9.SelectionForeColor = System.Drawing.SystemColors.HighlightText;
            dataGridViewCellStyle9.WrapMode = System.Windows.Forms.DataGridViewTriState.True;
            this.dgvCapacidades.RowHeadersDefaultCellStyle = dataGridViewCellStyle9;
            this.dgvCapacidades.RowHeadersVisible = false;
            this.dgvCapacidades.RowHeadersWidthSizeMode = System.Windows.Forms.DataGridViewRowHeadersWidthSizeMode.AutoSizeToDisplayedHeaders;
            dataGridViewCellStyle10.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleCenter;
            dataGridViewCellStyle10.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(31)))), ((int)(((byte)(33)))), ((int)(((byte)(37)))));
            dataGridViewCellStyle10.ForeColor = System.Drawing.Color.White;
            dataGridViewCellStyle10.SelectionBackColor = System.Drawing.Color.CornflowerBlue;
            dataGridViewCellStyle10.SelectionForeColor = System.Drawing.Color.White;
            this.dgvCapacidades.RowsDefaultCellStyle = dataGridViewCellStyle10;
            this.dgvCapacidades.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
            this.dgvCapacidades.Size = new System.Drawing.Size(423, 353);
            this.dgvCapacidades.TabIndex = 1;
            // 
            // tableLayoutPanel1
            // 
            this.tableLayoutPanel1.Anchor = ((System.Windows.Forms.AnchorStyles)((((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom) 
            | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.tableLayoutPanel1.AutoSizeMode = System.Windows.Forms.AutoSizeMode.GrowAndShrink;
            this.tableLayoutPanel1.ColumnCount = 8;
            this.tableLayoutPanel1.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 18.58108F));
            this.tableLayoutPanel1.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 19.48198F));
            this.tableLayoutPanel1.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 9.009009F));
            this.tableLayoutPanel1.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 2.924634F));
            this.tableLayoutPanel1.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 15.41057F));
            this.tableLayoutPanel1.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 10.34871F));
            this.tableLayoutPanel1.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 16.53543F));
            this.tableLayoutPanel1.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 7.536558F));
            this.tableLayoutPanel1.Controls.Add(this.dgvCapacidades, 0, 3);
            this.tableLayoutPanel1.Controls.Add(this.dtpFechaCapacidades, 0, 2);
            this.tableLayoutPanel1.Controls.Add(this.btnBuscarCapacidad, 2, 2);
            this.tableLayoutPanel1.Controls.Add(this.btnExportarCapacidadesExcel, 0, 1);
            this.tableLayoutPanel1.Controls.Add(this.dgvCupos, 4, 3);
            this.tableLayoutPanel1.Controls.Add(this.cbServicio, 6, 2);
            this.tableLayoutPanel1.Controls.Add(this.dtpFechaCupos, 4, 2);
            this.tableLayoutPanel1.Controls.Add(this.btnBuscarCupos, 7, 2);
            this.tableLayoutPanel1.Controls.Add(this.lblCupos, 4, 0);
            this.tableLayoutPanel1.Controls.Add(this.lblCapacidades, 0, 0);
            this.tableLayoutPanel1.Controls.Add(this.btnExportarCuposPDF, 4, 1);
            this.tableLayoutPanel1.Controls.Add(this.btnExportarCuposExcel, 5, 1);
            this.tableLayoutPanel1.Controls.Add(this.btnExportarCapacidadesPDF, 1, 1);
            this.tableLayoutPanel1.GrowStyle = System.Windows.Forms.TableLayoutPanelGrowStyle.AddColumns;
            this.tableLayoutPanel1.Location = new System.Drawing.Point(12, 12);
            this.tableLayoutPanel1.Name = "tableLayoutPanel1";
            this.tableLayoutPanel1.RowCount = 4;
            this.tableLayoutPanel1.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 7.943477F));
            this.tableLayoutPanel1.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 12.09862F));
            this.tableLayoutPanel1.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 11.10693F));
            this.tableLayoutPanel1.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 68.85098F));
            this.tableLayoutPanel1.Size = new System.Drawing.Size(913, 519);
            this.tableLayoutPanel1.TabIndex = 2;
            // 
            // dtpFechaCapacidades
            // 
            this.dtpFechaCapacidades.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Left | System.Windows.Forms.AnchorStyles.Right)));
            this.dtpFechaCapacidades.BackColor = System.Drawing.Color.Transparent;
            this.dtpFechaCapacidades.BorderRadius = 17;
            this.dtpFechaCapacidades.CalendarForeColor = System.Drawing.Color.White;
            this.dtpFechaCapacidades.CalendarTitleBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(22)))), ((int)(((byte)(23)))), ((int)(((byte)(27)))));
            this.dtpFechaCapacidades.CalendarTitleForeColor = System.Drawing.Color.White;
            this.dtpFechaCapacidades.CalendarTrailingForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(22)))), ((int)(((byte)(23)))), ((int)(((byte)(27)))));
            this.dtpFechaCapacidades.Color = System.Drawing.Color.FromArgb(((int)(((byte)(31)))), ((int)(((byte)(33)))), ((int)(((byte)(37)))));
            this.tableLayoutPanel1.SetColumnSpan(this.dtpFechaCapacidades, 2);
            this.dtpFechaCapacidades.CustomFormat = "dd/MM/yyyy";
            this.dtpFechaCapacidades.DateBorderThickness = Bunifu.UI.WinForms.BunifuDatePicker.BorderThickness.Thin;
            this.dtpFechaCapacidades.DateTextAlign = Bunifu.UI.WinForms.BunifuDatePicker.TextAlign.Left;
            this.dtpFechaCapacidades.DisabledColor = System.Drawing.Color.Gray;
            this.dtpFechaCapacidades.DisplayWeekNumbers = false;
            this.dtpFechaCapacidades.DPHeight = 0;
            this.dtpFechaCapacidades.DropDownAlign = System.Windows.Forms.LeftRightAlignment.Right;
            this.dtpFechaCapacidades.FillDatePicker = true;
            this.dtpFechaCapacidades.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.dtpFechaCapacidades.ForeColor = System.Drawing.Color.White;
            this.dtpFechaCapacidades.Icon = ((System.Drawing.Image)(resources.GetObject("dtpFechaCapacidades.Icon")));
            this.dtpFechaCapacidades.IconColor = System.Drawing.Color.White;
            this.dtpFechaCapacidades.IconLocation = Bunifu.UI.WinForms.BunifuDatePicker.Indicator.Right;
            this.dtpFechaCapacidades.LeftTextMargin = 5;
            this.dtpFechaCapacidades.Location = new System.Drawing.Point(3, 115);
            this.dtpFechaCapacidades.MaxDate = new System.DateTime(2100, 12, 31, 0, 0, 0, 0);
            this.dtpFechaCapacidades.MinDate = new System.DateTime(1900, 1, 1, 0, 0, 0, 0);
            this.dtpFechaCapacidades.MinimumSize = new System.Drawing.Size(4, 32);
            this.dtpFechaCapacidades.Name = "dtpFechaCapacidades";
            this.dtpFechaCapacidades.Size = new System.Drawing.Size(341, 32);
            this.dtpFechaCapacidades.TabIndex = 160;
            this.dtpFechaCapacidades.Value = new System.DateTime(2021, 9, 1, 0, 0, 0, 0);
            // 
            // btnBuscarCapacidad
            // 
            this.btnBuscarCapacidad.AllowAnimations = true;
            this.btnBuscarCapacidad.AllowMouseEffects = true;
            this.btnBuscarCapacidad.AllowToggling = false;
            this.btnBuscarCapacidad.Anchor = System.Windows.Forms.AnchorStyles.Left;
            this.btnBuscarCapacidad.AnimationSpeed = 200;
            this.btnBuscarCapacidad.AutoGenerateColors = false;
            this.btnBuscarCapacidad.AutoRoundBorders = false;
            this.btnBuscarCapacidad.AutoSizeLeftIcon = true;
            this.btnBuscarCapacidad.AutoSizeRightIcon = true;
            this.btnBuscarCapacidad.BackColor = System.Drawing.Color.Transparent;
            this.btnBuscarCapacidad.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(126)))), ((int)(((byte)(249)))));
            this.btnBuscarCapacidad.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnBuscarCapacidad.BackgroundImage")));
            this.btnBuscarCapacidad.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnBuscarCapacidad.ButtonText = " ";
            this.btnBuscarCapacidad.ButtonTextMarginLeft = 0;
            this.btnBuscarCapacidad.ColorContrastOnClick = 45;
            this.btnBuscarCapacidad.ColorContrastOnHover = 45;
            this.btnBuscarCapacidad.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.btnBuscarCapacidad.CustomizableEdges = borderEdges1;
            this.btnBuscarCapacidad.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnBuscarCapacidad.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnBuscarCapacidad.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnBuscarCapacidad.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnBuscarCapacidad.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnBuscarCapacidad.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.btnBuscarCapacidad.ForeColor = System.Drawing.Color.White;
            this.btnBuscarCapacidad.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnBuscarCapacidad.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnBuscarCapacidad.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnBuscarCapacidad.IconMarginLeft = 11;
            this.btnBuscarCapacidad.IconPadding = 10;
            this.btnBuscarCapacidad.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnBuscarCapacidad.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnBuscarCapacidad.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnBuscarCapacidad.IconSize = 25;
            this.btnBuscarCapacidad.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(126)))), ((int)(((byte)(249)))));
            this.btnBuscarCapacidad.IdleBorderRadius = 40;
            this.btnBuscarCapacidad.IdleBorderThickness = 2;
            this.btnBuscarCapacidad.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(126)))), ((int)(((byte)(249)))));
            this.btnBuscarCapacidad.IdleIconLeftImage = null;
            this.btnBuscarCapacidad.IdleIconRightImage = ((System.Drawing.Image)(resources.GetObject("btnBuscarCapacidad.IdleIconRightImage")));
            this.btnBuscarCapacidad.IndicateFocus = false;
            this.btnBuscarCapacidad.Location = new System.Drawing.Point(347, 107);
            this.btnBuscarCapacidad.Margin = new System.Windows.Forms.Padding(0);
            this.btnBuscarCapacidad.Name = "btnBuscarCapacidad";
            this.btnBuscarCapacidad.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnBuscarCapacidad.OnDisabledState.BorderRadius = 40;
            this.btnBuscarCapacidad.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnBuscarCapacidad.OnDisabledState.BorderThickness = 2;
            this.btnBuscarCapacidad.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnBuscarCapacidad.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnBuscarCapacidad.OnDisabledState.IconLeftImage = null;
            this.btnBuscarCapacidad.OnDisabledState.IconRightImage = null;
            this.btnBuscarCapacidad.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(126)))), ((int)(((byte)(255)))));
            this.btnBuscarCapacidad.onHoverState.BorderRadius = 40;
            this.btnBuscarCapacidad.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnBuscarCapacidad.onHoverState.BorderThickness = 2;
            this.btnBuscarCapacidad.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(126)))), ((int)(((byte)(255)))));
            this.btnBuscarCapacidad.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnBuscarCapacidad.onHoverState.IconLeftImage = null;
            this.btnBuscarCapacidad.onHoverState.IconRightImage = null;
            this.btnBuscarCapacidad.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(126)))), ((int)(((byte)(249)))));
            this.btnBuscarCapacidad.OnIdleState.BorderRadius = 40;
            this.btnBuscarCapacidad.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnBuscarCapacidad.OnIdleState.BorderThickness = 2;
            this.btnBuscarCapacidad.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(126)))), ((int)(((byte)(249)))));
            this.btnBuscarCapacidad.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnBuscarCapacidad.OnIdleState.IconLeftImage = null;
            this.btnBuscarCapacidad.OnIdleState.IconRightImage = ((System.Drawing.Image)(resources.GetObject("btnBuscarCapacidad.OnIdleState.IconRightImage")));
            this.btnBuscarCapacidad.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(126)))), ((int)(((byte)(249)))));
            this.btnBuscarCapacidad.OnPressedState.BorderRadius = 40;
            this.btnBuscarCapacidad.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnBuscarCapacidad.OnPressedState.BorderThickness = 2;
            this.btnBuscarCapacidad.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(126)))), ((int)(((byte)(249)))));
            this.btnBuscarCapacidad.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnBuscarCapacidad.OnPressedState.IconLeftImage = null;
            this.btnBuscarCapacidad.OnPressedState.IconRightImage = null;
            this.btnBuscarCapacidad.Size = new System.Drawing.Size(50, 48);
            this.btnBuscarCapacidad.TabIndex = 13;
            this.btnBuscarCapacidad.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnBuscarCapacidad.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnBuscarCapacidad.TextMarginLeft = 0;
            this.btnBuscarCapacidad.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnBuscarCapacidad.UseDefaultRadiusAndThickness = true;
            this.btnBuscarCapacidad.Click += new System.EventHandler(this.btnBuscarCapacidad_Click);
            // 
            // btnExportarCapacidadesExcel
            // 
            this.btnExportarCapacidadesExcel.AllowAnimations = true;
            this.btnExportarCapacidadesExcel.AllowMouseEffects = true;
            this.btnExportarCapacidadesExcel.AllowToggling = false;
            this.btnExportarCapacidadesExcel.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Left | System.Windows.Forms.AnchorStyles.Right)));
            this.btnExportarCapacidadesExcel.AnimationSpeed = 200;
            this.btnExportarCapacidadesExcel.AutoGenerateColors = false;
            this.btnExportarCapacidadesExcel.AutoRoundBorders = false;
            this.btnExportarCapacidadesExcel.AutoSizeLeftIcon = true;
            this.btnExportarCapacidadesExcel.AutoSizeRightIcon = true;
            this.btnExportarCapacidadesExcel.BackColor = System.Drawing.Color.Transparent;
            this.btnExportarCapacidadesExcel.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(22)))), ((int)(((byte)(23)))), ((int)(((byte)(27)))));
            this.btnExportarCapacidadesExcel.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnExportarCapacidadesExcel.BackgroundImage")));
            this.btnExportarCapacidadesExcel.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnExportarCapacidadesExcel.ButtonText = " Exportar a Excel";
            this.btnExportarCapacidadesExcel.ButtonTextMarginLeft = 0;
            this.btnExportarCapacidadesExcel.ColorContrastOnClick = 45;
            this.btnExportarCapacidadesExcel.ColorContrastOnHover = 45;
            this.btnExportarCapacidadesExcel.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            this.btnExportarCapacidadesExcel.CustomizableEdges = borderEdges2;
            this.btnExportarCapacidadesExcel.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnExportarCapacidadesExcel.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnExportarCapacidadesExcel.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnExportarCapacidadesExcel.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnExportarCapacidadesExcel.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnExportarCapacidadesExcel.Font = new System.Drawing.Font("Segoe UI Semibold", 9F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnExportarCapacidadesExcel.ForeColor = System.Drawing.Color.White;
            this.btnExportarCapacidadesExcel.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnExportarCapacidadesExcel.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnExportarCapacidadesExcel.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnExportarCapacidadesExcel.IconMarginLeft = 11;
            this.btnExportarCapacidadesExcel.IconPadding = 10;
            this.btnExportarCapacidadesExcel.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnExportarCapacidadesExcel.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnExportarCapacidadesExcel.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnExportarCapacidadesExcel.IconSize = 25;
            this.btnExportarCapacidadesExcel.IdleBorderColor = System.Drawing.Color.Green;
            this.btnExportarCapacidadesExcel.IdleBorderRadius = 40;
            this.btnExportarCapacidadesExcel.IdleBorderThickness = 2;
            this.btnExportarCapacidadesExcel.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(22)))), ((int)(((byte)(23)))), ((int)(((byte)(27)))));
            this.btnExportarCapacidadesExcel.IdleIconLeftImage = ((System.Drawing.Image)(resources.GetObject("btnExportarCapacidadesExcel.IdleIconLeftImage")));
            this.btnExportarCapacidadesExcel.IdleIconRightImage = null;
            this.btnExportarCapacidadesExcel.IndicateFocus = false;
            this.btnExportarCapacidadesExcel.Location = new System.Drawing.Point(3, 45);
            this.btnExportarCapacidadesExcel.Margin = new System.Windows.Forms.Padding(3, 3, 3, 10);
            this.btnExportarCapacidadesExcel.Name = "btnExportarCapacidadesExcel";
            this.btnExportarCapacidadesExcel.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnExportarCapacidadesExcel.OnDisabledState.BorderRadius = 40;
            this.btnExportarCapacidadesExcel.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnExportarCapacidadesExcel.OnDisabledState.BorderThickness = 2;
            this.btnExportarCapacidadesExcel.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnExportarCapacidadesExcel.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnExportarCapacidadesExcel.OnDisabledState.IconLeftImage = null;
            this.btnExportarCapacidadesExcel.OnDisabledState.IconRightImage = null;
            this.btnExportarCapacidadesExcel.onHoverState.BorderColor = System.Drawing.Color.Green;
            this.btnExportarCapacidadesExcel.onHoverState.BorderRadius = 40;
            this.btnExportarCapacidadesExcel.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnExportarCapacidadesExcel.onHoverState.BorderThickness = 2;
            this.btnExportarCapacidadesExcel.onHoverState.FillColor = System.Drawing.Color.Green;
            this.btnExportarCapacidadesExcel.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnExportarCapacidadesExcel.onHoverState.IconLeftImage = null;
            this.btnExportarCapacidadesExcel.onHoverState.IconRightImage = null;
            this.btnExportarCapacidadesExcel.OnIdleState.BorderColor = System.Drawing.Color.Green;
            this.btnExportarCapacidadesExcel.OnIdleState.BorderRadius = 40;
            this.btnExportarCapacidadesExcel.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnExportarCapacidadesExcel.OnIdleState.BorderThickness = 2;
            this.btnExportarCapacidadesExcel.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(22)))), ((int)(((byte)(23)))), ((int)(((byte)(27)))));
            this.btnExportarCapacidadesExcel.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnExportarCapacidadesExcel.OnIdleState.IconLeftImage = ((System.Drawing.Image)(resources.GetObject("btnExportarCapacidadesExcel.OnIdleState.IconLeftImage")));
            this.btnExportarCapacidadesExcel.OnIdleState.IconRightImage = null;
            this.btnExportarCapacidadesExcel.OnPressedState.BorderColor = System.Drawing.Color.Green;
            this.btnExportarCapacidadesExcel.OnPressedState.BorderRadius = 40;
            this.btnExportarCapacidadesExcel.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnExportarCapacidadesExcel.OnPressedState.BorderThickness = 2;
            this.btnExportarCapacidadesExcel.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(22)))), ((int)(((byte)(23)))), ((int)(((byte)(27)))));
            this.btnExportarCapacidadesExcel.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnExportarCapacidadesExcel.OnPressedState.IconLeftImage = null;
            this.btnExportarCapacidadesExcel.OnPressedState.IconRightImage = null;
            this.btnExportarCapacidadesExcel.Size = new System.Drawing.Size(163, 47);
            this.btnExportarCapacidadesExcel.TabIndex = 167;
            this.btnExportarCapacidadesExcel.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnExportarCapacidadesExcel.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnExportarCapacidadesExcel.TextMarginLeft = 0;
            this.btnExportarCapacidadesExcel.TextPadding = new System.Windows.Forms.Padding(5, 0, 0, 0);
            this.btnExportarCapacidadesExcel.UseDefaultRadiusAndThickness = true;
            this.btnExportarCapacidadesExcel.Click += new System.EventHandler(this.btnExportarCapacidadesExcel_Click);
            // 
            // dgvCupos
            // 
            this.dgvCupos.AllowUserToAddRows = false;
            this.dgvCupos.AllowUserToDeleteRows = false;
            dataGridViewCellStyle3.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleCenter;
            dataGridViewCellStyle3.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(27)))), ((int)(((byte)(29)))), ((int)(((byte)(36)))));
            this.dgvCupos.AlternatingRowsDefaultCellStyle = dataGridViewCellStyle3;
            this.dgvCupos.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.Fill;
            this.dgvCupos.AutoSizeRowsMode = System.Windows.Forms.DataGridViewAutoSizeRowsMode.AllCells;
            this.dgvCupos.BackgroundColor = System.Drawing.Color.FromArgb(((int)(((byte)(31)))), ((int)(((byte)(33)))), ((int)(((byte)(37)))));
            this.dgvCupos.CellBorderStyle = System.Windows.Forms.DataGridViewCellBorderStyle.None;
            this.dgvCupos.ColumnHeadersBorderStyle = System.Windows.Forms.DataGridViewHeaderBorderStyle.None;
            dataGridViewCellStyle4.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleCenter;
            dataGridViewCellStyle4.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(126)))), ((int)(((byte)(249)))));
            dataGridViewCellStyle4.Font = new System.Drawing.Font("Microsoft Sans Serif", 11.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            dataGridViewCellStyle4.ForeColor = System.Drawing.Color.White;
            dataGridViewCellStyle4.SelectionBackColor = System.Drawing.SystemColors.HotTrack;
            dataGridViewCellStyle4.SelectionForeColor = System.Drawing.Color.White;
            dataGridViewCellStyle4.WrapMode = System.Windows.Forms.DataGridViewTriState.True;
            this.dgvCupos.ColumnHeadersDefaultCellStyle = dataGridViewCellStyle4;
            this.dgvCupos.ColumnHeadersHeight = 50;
            this.dgvCupos.ColumnHeadersHeightSizeMode = System.Windows.Forms.DataGridViewColumnHeadersHeightSizeMode.DisableResizing;
            this.tableLayoutPanel1.SetColumnSpan(this.dgvCupos, 4);
            dataGridViewCellStyle5.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleCenter;
            dataGridViewCellStyle5.BackColor = System.Drawing.Color.Black;
            dataGridViewCellStyle5.Font = new System.Drawing.Font("Comic Sans MS", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            dataGridViewCellStyle5.ForeColor = System.Drawing.Color.White;
            dataGridViewCellStyle5.SelectionBackColor = System.Drawing.SystemColors.GradientActiveCaption;
            dataGridViewCellStyle5.SelectionForeColor = System.Drawing.SystemColors.HighlightText;
            dataGridViewCellStyle5.WrapMode = System.Windows.Forms.DataGridViewTriState.False;
            this.dgvCupos.DefaultCellStyle = dataGridViewCellStyle5;
            this.dgvCupos.Dock = System.Windows.Forms.DockStyle.Fill;
            this.dgvCupos.EnableHeadersVisualStyles = false;
            this.dgvCupos.GridColor = System.Drawing.Color.SteelBlue;
            this.dgvCupos.Location = new System.Drawing.Point(458, 163);
            this.dgvCupos.Name = "dgvCupos";
            this.dgvCupos.ReadOnly = true;
            this.dgvCupos.RowHeadersBorderStyle = System.Windows.Forms.DataGridViewHeaderBorderStyle.None;
            dataGridViewCellStyle6.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleCenter;
            dataGridViewCellStyle6.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(39)))), ((int)(((byte)(41)))), ((int)(((byte)(61)))));
            dataGridViewCellStyle6.Font = new System.Drawing.Font("Comic Sans MS", 9.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            dataGridViewCellStyle6.ForeColor = System.Drawing.Color.White;
            dataGridViewCellStyle6.SelectionBackColor = System.Drawing.SystemColors.Highlight;
            dataGridViewCellStyle6.SelectionForeColor = System.Drawing.SystemColors.HighlightText;
            dataGridViewCellStyle6.WrapMode = System.Windows.Forms.DataGridViewTriState.True;
            this.dgvCupos.RowHeadersDefaultCellStyle = dataGridViewCellStyle6;
            this.dgvCupos.RowHeadersVisible = false;
            this.dgvCupos.RowHeadersWidthSizeMode = System.Windows.Forms.DataGridViewRowHeadersWidthSizeMode.AutoSizeToDisplayedHeaders;
            dataGridViewCellStyle7.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleCenter;
            dataGridViewCellStyle7.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(31)))), ((int)(((byte)(33)))), ((int)(((byte)(37)))));
            dataGridViewCellStyle7.ForeColor = System.Drawing.Color.White;
            dataGridViewCellStyle7.SelectionBackColor = System.Drawing.Color.CornflowerBlue;
            dataGridViewCellStyle7.SelectionForeColor = System.Drawing.Color.White;
            this.dgvCupos.RowsDefaultCellStyle = dataGridViewCellStyle7;
            this.dgvCupos.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
            this.dgvCupos.Size = new System.Drawing.Size(452, 353);
            this.dgvCupos.TabIndex = 3;
            // 
            // cbServicio
            // 
            this.cbServicio.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Left | System.Windows.Forms.AnchorStyles.Right)));
            this.cbServicio.BackColor = System.Drawing.Color.Transparent;
            this.cbServicio.BackgroundColor = System.Drawing.Color.FromArgb(((int)(((byte)(31)))), ((int)(((byte)(33)))), ((int)(((byte)(37)))));
            this.cbServicio.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(31)))), ((int)(((byte)(33)))), ((int)(((byte)(37)))));
            this.cbServicio.BorderRadius = 17;
            this.cbServicio.Color = System.Drawing.Color.FromArgb(((int)(((byte)(31)))), ((int)(((byte)(33)))), ((int)(((byte)(37)))));
            this.cbServicio.Direction = Bunifu.UI.WinForms.BunifuDropdown.Directions.Down;
            this.cbServicio.DisabledBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            this.cbServicio.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.cbServicio.DisabledColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            this.cbServicio.DisabledForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            this.cbServicio.DisabledIndicatorColor = System.Drawing.Color.DarkGray;
            this.cbServicio.DrawMode = System.Windows.Forms.DrawMode.OwnerDrawFixed;
            this.cbServicio.DropdownBorderThickness = Bunifu.UI.WinForms.BunifuDropdown.BorderThickness.Thin;
            this.cbServicio.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.cbServicio.DropDownTextAlign = Bunifu.UI.WinForms.BunifuDropdown.TextAlign.Left;
            this.cbServicio.FillDropDown = true;
            this.cbServicio.FillIndicator = false;
            this.cbServicio.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.cbServicio.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.cbServicio.ForeColor = System.Drawing.Color.White;
            this.cbServicio.FormattingEnabled = true;
            this.cbServicio.Icon = null;
            this.cbServicio.IndicatorAlignment = Bunifu.UI.WinForms.BunifuDropdown.Indicator.Right;
            this.cbServicio.IndicatorColor = System.Drawing.Color.Gray;
            this.cbServicio.IndicatorLocation = Bunifu.UI.WinForms.BunifuDropdown.Indicator.Right;
            this.cbServicio.ItemBackColor = System.Drawing.Color.White;
            this.cbServicio.ItemBorderColor = System.Drawing.Color.White;
            this.cbServicio.ItemForeColor = System.Drawing.Color.Black;
            this.cbServicio.ItemHeight = 26;
            this.cbServicio.ItemHighLightColor = System.Drawing.Color.DodgerBlue;
            this.cbServicio.ItemHighLightForeColor = System.Drawing.Color.White;
            this.cbServicio.ItemTopMargin = 3;
            this.cbServicio.Location = new System.Drawing.Point(692, 115);
            this.cbServicio.Name = "cbServicio";
            this.cbServicio.Size = new System.Drawing.Size(145, 32);
            this.cbServicio.TabIndex = 164;
            this.cbServicio.Text = "Servicio";
            this.cbServicio.TextAlignment = Bunifu.UI.WinForms.BunifuDropdown.TextAlign.Left;
            this.cbServicio.TextLeftMargin = 5;
            // 
            // dtpFechaCupos
            // 
            this.dtpFechaCupos.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Left | System.Windows.Forms.AnchorStyles.Right)));
            this.dtpFechaCupos.BackColor = System.Drawing.Color.Transparent;
            this.dtpFechaCupos.BorderRadius = 17;
            this.dtpFechaCupos.CalendarForeColor = System.Drawing.Color.White;
            this.dtpFechaCupos.CalendarTitleBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(22)))), ((int)(((byte)(23)))), ((int)(((byte)(27)))));
            this.dtpFechaCupos.CalendarTitleForeColor = System.Drawing.Color.White;
            this.dtpFechaCupos.CalendarTrailingForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(22)))), ((int)(((byte)(23)))), ((int)(((byte)(27)))));
            this.dtpFechaCupos.Color = System.Drawing.Color.FromArgb(((int)(((byte)(31)))), ((int)(((byte)(33)))), ((int)(((byte)(37)))));
            this.tableLayoutPanel1.SetColumnSpan(this.dtpFechaCupos, 2);
            this.dtpFechaCupos.CustomFormat = "dd/MM/yyyy";
            this.dtpFechaCupos.DateBorderThickness = Bunifu.UI.WinForms.BunifuDatePicker.BorderThickness.Thin;
            this.dtpFechaCupos.DateTextAlign = Bunifu.UI.WinForms.BunifuDatePicker.TextAlign.Left;
            this.dtpFechaCupos.DisabledColor = System.Drawing.Color.Gray;
            this.dtpFechaCupos.DisplayWeekNumbers = false;
            this.dtpFechaCupos.DPHeight = 0;
            this.dtpFechaCupos.DropDownAlign = System.Windows.Forms.LeftRightAlignment.Right;
            this.dtpFechaCupos.FillDatePicker = true;
            this.dtpFechaCupos.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.dtpFechaCupos.ForeColor = System.Drawing.Color.White;
            this.dtpFechaCupos.Icon = ((System.Drawing.Image)(resources.GetObject("dtpFechaCupos.Icon")));
            this.dtpFechaCupos.IconColor = System.Drawing.Color.White;
            this.dtpFechaCupos.IconLocation = Bunifu.UI.WinForms.BunifuDatePicker.Indicator.Right;
            this.dtpFechaCupos.LeftTextMargin = 5;
            this.dtpFechaCupos.Location = new System.Drawing.Point(458, 115);
            this.dtpFechaCupos.MaxDate = new System.DateTime(2100, 12, 31, 0, 0, 0, 0);
            this.dtpFechaCupos.MinDate = new System.DateTime(1900, 1, 1, 0, 0, 0, 0);
            this.dtpFechaCupos.MinimumSize = new System.Drawing.Size(4, 32);
            this.dtpFechaCupos.Name = "dtpFechaCupos";
            this.dtpFechaCupos.Size = new System.Drawing.Size(228, 32);
            this.dtpFechaCupos.TabIndex = 161;
            this.dtpFechaCupos.Value = new System.DateTime(2021, 9, 1, 0, 0, 0, 0);
            // 
            // btnBuscarCupos
            // 
            this.btnBuscarCupos.AllowAnimations = true;
            this.btnBuscarCupos.AllowMouseEffects = true;
            this.btnBuscarCupos.AllowToggling = false;
            this.btnBuscarCupos.Anchor = System.Windows.Forms.AnchorStyles.Left;
            this.btnBuscarCupos.AnimationSpeed = 200;
            this.btnBuscarCupos.AutoGenerateColors = false;
            this.btnBuscarCupos.AutoRoundBorders = false;
            this.btnBuscarCupos.AutoSizeLeftIcon = true;
            this.btnBuscarCupos.AutoSizeRightIcon = true;
            this.btnBuscarCupos.BackColor = System.Drawing.Color.Transparent;
            this.btnBuscarCupos.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(126)))), ((int)(((byte)(249)))));
            this.btnBuscarCupos.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnBuscarCupos.BackgroundImage")));
            this.btnBuscarCupos.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnBuscarCupos.ButtonText = " ";
            this.btnBuscarCupos.ButtonTextMarginLeft = 0;
            this.btnBuscarCupos.ColorContrastOnClick = 45;
            this.btnBuscarCupos.ColorContrastOnHover = 45;
            this.btnBuscarCupos.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges3.BottomLeft = true;
            borderEdges3.BottomRight = true;
            borderEdges3.TopLeft = true;
            borderEdges3.TopRight = true;
            this.btnBuscarCupos.CustomizableEdges = borderEdges3;
            this.btnBuscarCupos.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnBuscarCupos.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnBuscarCupos.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnBuscarCupos.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnBuscarCupos.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnBuscarCupos.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.btnBuscarCupos.ForeColor = System.Drawing.Color.White;
            this.btnBuscarCupos.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnBuscarCupos.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnBuscarCupos.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnBuscarCupos.IconMarginLeft = 11;
            this.btnBuscarCupos.IconPadding = 10;
            this.btnBuscarCupos.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnBuscarCupos.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnBuscarCupos.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnBuscarCupos.IconSize = 25;
            this.btnBuscarCupos.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(126)))), ((int)(((byte)(249)))));
            this.btnBuscarCupos.IdleBorderRadius = 40;
            this.btnBuscarCupos.IdleBorderThickness = 2;
            this.btnBuscarCupos.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(126)))), ((int)(((byte)(249)))));
            this.btnBuscarCupos.IdleIconLeftImage = null;
            this.btnBuscarCupos.IdleIconRightImage = ((System.Drawing.Image)(resources.GetObject("btnBuscarCupos.IdleIconRightImage")));
            this.btnBuscarCupos.IndicateFocus = false;
            this.btnBuscarCupos.Location = new System.Drawing.Point(840, 107);
            this.btnBuscarCupos.Margin = new System.Windows.Forms.Padding(0);
            this.btnBuscarCupos.Name = "btnBuscarCupos";
            this.btnBuscarCupos.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnBuscarCupos.OnDisabledState.BorderRadius = 40;
            this.btnBuscarCupos.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnBuscarCupos.OnDisabledState.BorderThickness = 2;
            this.btnBuscarCupos.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnBuscarCupos.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnBuscarCupos.OnDisabledState.IconLeftImage = null;
            this.btnBuscarCupos.OnDisabledState.IconRightImage = null;
            this.btnBuscarCupos.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(126)))), ((int)(((byte)(255)))));
            this.btnBuscarCupos.onHoverState.BorderRadius = 40;
            this.btnBuscarCupos.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnBuscarCupos.onHoverState.BorderThickness = 2;
            this.btnBuscarCupos.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(126)))), ((int)(((byte)(255)))));
            this.btnBuscarCupos.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnBuscarCupos.onHoverState.IconLeftImage = null;
            this.btnBuscarCupos.onHoverState.IconRightImage = null;
            this.btnBuscarCupos.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(126)))), ((int)(((byte)(249)))));
            this.btnBuscarCupos.OnIdleState.BorderRadius = 40;
            this.btnBuscarCupos.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnBuscarCupos.OnIdleState.BorderThickness = 2;
            this.btnBuscarCupos.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(126)))), ((int)(((byte)(249)))));
            this.btnBuscarCupos.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnBuscarCupos.OnIdleState.IconLeftImage = null;
            this.btnBuscarCupos.OnIdleState.IconRightImage = ((System.Drawing.Image)(resources.GetObject("btnBuscarCupos.OnIdleState.IconRightImage")));
            this.btnBuscarCupos.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(126)))), ((int)(((byte)(249)))));
            this.btnBuscarCupos.OnPressedState.BorderRadius = 40;
            this.btnBuscarCupos.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnBuscarCupos.OnPressedState.BorderThickness = 2;
            this.btnBuscarCupos.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(126)))), ((int)(((byte)(249)))));
            this.btnBuscarCupos.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnBuscarCupos.OnPressedState.IconLeftImage = null;
            this.btnBuscarCupos.OnPressedState.IconRightImage = null;
            this.btnBuscarCupos.Size = new System.Drawing.Size(50, 48);
            this.btnBuscarCupos.TabIndex = 14;
            this.btnBuscarCupos.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnBuscarCupos.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnBuscarCupos.TextMarginLeft = 0;
            this.btnBuscarCupos.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnBuscarCupos.UseDefaultRadiusAndThickness = true;
            this.btnBuscarCupos.Click += new System.EventHandler(this.btnBuscarCupos_Click);
            // 
            // lblCupos
            // 
            this.lblCupos.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Left | System.Windows.Forms.AnchorStyles.Right)));
            this.lblCupos.AutoSize = true;
            this.tableLayoutPanel1.SetColumnSpan(this.lblCupos, 4);
            this.lblCupos.Font = new System.Drawing.Font("Segoe UI Light", 20F);
            this.lblCupos.ForeColor = System.Drawing.Color.White;
            this.lblCupos.Location = new System.Drawing.Point(458, 2);
            this.lblCupos.Name = "lblCupos";
            this.lblCupos.Size = new System.Drawing.Size(452, 37);
            this.lblCupos.TabIndex = 163;
            this.lblCupos.Text = "Cupos";
            this.lblCupos.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            // 
            // lblCapacidades
            // 
            this.lblCapacidades.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Left | System.Windows.Forms.AnchorStyles.Right)));
            this.lblCapacidades.AutoSize = true;
            this.tableLayoutPanel1.SetColumnSpan(this.lblCapacidades, 3);
            this.lblCapacidades.Font = new System.Drawing.Font("Segoe UI Light", 20F);
            this.lblCapacidades.ForeColor = System.Drawing.Color.White;
            this.lblCapacidades.Location = new System.Drawing.Point(3, 2);
            this.lblCapacidades.Name = "lblCapacidades";
            this.lblCapacidades.Size = new System.Drawing.Size(423, 37);
            this.lblCapacidades.TabIndex = 162;
            this.lblCapacidades.Text = "Capacidades";
            this.lblCapacidades.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            // 
            // btnExportarCuposPDF
            // 
            this.btnExportarCuposPDF.AllowAnimations = true;
            this.btnExportarCuposPDF.AllowMouseEffects = true;
            this.btnExportarCuposPDF.AllowToggling = false;
            this.btnExportarCuposPDF.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Left | System.Windows.Forms.AnchorStyles.Right)));
            this.btnExportarCuposPDF.AnimationSpeed = 200;
            this.btnExportarCuposPDF.AutoGenerateColors = false;
            this.btnExportarCuposPDF.AutoRoundBorders = false;
            this.btnExportarCuposPDF.AutoSizeLeftIcon = true;
            this.btnExportarCuposPDF.AutoSizeRightIcon = true;
            this.btnExportarCuposPDF.BackColor = System.Drawing.Color.Transparent;
            this.btnExportarCuposPDF.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(22)))), ((int)(((byte)(23)))), ((int)(((byte)(27)))));
            this.btnExportarCuposPDF.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnExportarCuposPDF.BackgroundImage")));
            this.btnExportarCuposPDF.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnExportarCuposPDF.ButtonText = " Exportar a PDF";
            this.btnExportarCuposPDF.ButtonTextMarginLeft = 0;
            this.btnExportarCuposPDF.ColorContrastOnClick = 45;
            this.btnExportarCuposPDF.ColorContrastOnHover = 45;
            this.btnExportarCuposPDF.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges4.BottomLeft = true;
            borderEdges4.BottomRight = true;
            borderEdges4.TopLeft = true;
            borderEdges4.TopRight = true;
            this.btnExportarCuposPDF.CustomizableEdges = borderEdges4;
            this.btnExportarCuposPDF.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnExportarCuposPDF.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnExportarCuposPDF.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnExportarCuposPDF.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnExportarCuposPDF.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnExportarCuposPDF.Font = new System.Drawing.Font("Segoe UI Semibold", 9F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnExportarCuposPDF.ForeColor = System.Drawing.Color.White;
            this.btnExportarCuposPDF.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnExportarCuposPDF.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnExportarCuposPDF.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnExportarCuposPDF.IconMarginLeft = 11;
            this.btnExportarCuposPDF.IconPadding = 10;
            this.btnExportarCuposPDF.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnExportarCuposPDF.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnExportarCuposPDF.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnExportarCuposPDF.IconSize = 25;
            this.btnExportarCuposPDF.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(231)))), ((int)(((byte)(76)))), ((int)(((byte)(80)))));
            this.btnExportarCuposPDF.IdleBorderRadius = 40;
            this.btnExportarCuposPDF.IdleBorderThickness = 2;
            this.btnExportarCuposPDF.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(22)))), ((int)(((byte)(23)))), ((int)(((byte)(27)))));
            this.btnExportarCuposPDF.IdleIconLeftImage = ((System.Drawing.Image)(resources.GetObject("btnExportarCuposPDF.IdleIconLeftImage")));
            this.btnExportarCuposPDF.IdleIconRightImage = null;
            this.btnExportarCuposPDF.IndicateFocus = false;
            this.btnExportarCuposPDF.Location = new System.Drawing.Point(458, 45);
            this.btnExportarCuposPDF.Margin = new System.Windows.Forms.Padding(3, 3, 3, 10);
            this.btnExportarCuposPDF.Name = "btnExportarCuposPDF";
            this.btnExportarCuposPDF.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnExportarCuposPDF.OnDisabledState.BorderRadius = 40;
            this.btnExportarCuposPDF.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnExportarCuposPDF.OnDisabledState.BorderThickness = 2;
            this.btnExportarCuposPDF.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnExportarCuposPDF.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnExportarCuposPDF.OnDisabledState.IconLeftImage = null;
            this.btnExportarCuposPDF.OnDisabledState.IconRightImage = null;
            this.btnExportarCuposPDF.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(231)))), ((int)(((byte)(76)))), ((int)(((byte)(80)))));
            this.btnExportarCuposPDF.onHoverState.BorderRadius = 40;
            this.btnExportarCuposPDF.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnExportarCuposPDF.onHoverState.BorderThickness = 2;
            this.btnExportarCuposPDF.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(231)))), ((int)(((byte)(76)))), ((int)(((byte)(80)))));
            this.btnExportarCuposPDF.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnExportarCuposPDF.onHoverState.IconLeftImage = null;
            this.btnExportarCuposPDF.onHoverState.IconRightImage = null;
            this.btnExportarCuposPDF.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(231)))), ((int)(((byte)(76)))), ((int)(((byte)(80)))));
            this.btnExportarCuposPDF.OnIdleState.BorderRadius = 40;
            this.btnExportarCuposPDF.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnExportarCuposPDF.OnIdleState.BorderThickness = 2;
            this.btnExportarCuposPDF.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(22)))), ((int)(((byte)(23)))), ((int)(((byte)(27)))));
            this.btnExportarCuposPDF.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnExportarCuposPDF.OnIdleState.IconLeftImage = ((System.Drawing.Image)(resources.GetObject("btnExportarCuposPDF.OnIdleState.IconLeftImage")));
            this.btnExportarCuposPDF.OnIdleState.IconRightImage = null;
            this.btnExportarCuposPDF.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(231)))), ((int)(((byte)(76)))), ((int)(((byte)(80)))));
            this.btnExportarCuposPDF.OnPressedState.BorderRadius = 40;
            this.btnExportarCuposPDF.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnExportarCuposPDF.OnPressedState.BorderThickness = 2;
            this.btnExportarCuposPDF.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(22)))), ((int)(((byte)(23)))), ((int)(((byte)(27)))));
            this.btnExportarCuposPDF.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnExportarCuposPDF.OnPressedState.IconLeftImage = null;
            this.btnExportarCuposPDF.OnPressedState.IconRightImage = null;
            this.btnExportarCuposPDF.Size = new System.Drawing.Size(134, 47);
            this.btnExportarCuposPDF.TabIndex = 166;
            this.btnExportarCuposPDF.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnExportarCuposPDF.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnExportarCuposPDF.TextMarginLeft = 0;
            this.btnExportarCuposPDF.TextPadding = new System.Windows.Forms.Padding(15, 0, 0, 0);
            this.btnExportarCuposPDF.UseDefaultRadiusAndThickness = true;
            this.btnExportarCuposPDF.Click += new System.EventHandler(this.btnExportarCuposPDF_Click);
            // 
            // btnExportarCuposExcel
            // 
            this.btnExportarCuposExcel.AllowAnimations = true;
            this.btnExportarCuposExcel.AllowMouseEffects = true;
            this.btnExportarCuposExcel.AllowToggling = false;
            this.btnExportarCuposExcel.Anchor = System.Windows.Forms.AnchorStyles.Left;
            this.btnExportarCuposExcel.AnimationSpeed = 200;
            this.btnExportarCuposExcel.AutoGenerateColors = false;
            this.btnExportarCuposExcel.AutoRoundBorders = false;
            this.btnExportarCuposExcel.AutoSizeLeftIcon = true;
            this.btnExportarCuposExcel.AutoSizeRightIcon = true;
            this.btnExportarCuposExcel.BackColor = System.Drawing.Color.Transparent;
            this.btnExportarCuposExcel.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(22)))), ((int)(((byte)(23)))), ((int)(((byte)(27)))));
            this.btnExportarCuposExcel.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnExportarCuposExcel.BackgroundImage")));
            this.btnExportarCuposExcel.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnExportarCuposExcel.ButtonText = " Exportar a Excel";
            this.btnExportarCuposExcel.ButtonTextMarginLeft = 0;
            this.btnExportarCuposExcel.ColorContrastOnClick = 45;
            this.btnExportarCuposExcel.ColorContrastOnHover = 45;
            this.tableLayoutPanel1.SetColumnSpan(this.btnExportarCuposExcel, 2);
            this.btnExportarCuposExcel.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges5.BottomLeft = true;
            borderEdges5.BottomRight = true;
            borderEdges5.TopLeft = true;
            borderEdges5.TopRight = true;
            this.btnExportarCuposExcel.CustomizableEdges = borderEdges5;
            this.btnExportarCuposExcel.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnExportarCuposExcel.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnExportarCuposExcel.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnExportarCuposExcel.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnExportarCuposExcel.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnExportarCuposExcel.Font = new System.Drawing.Font("Segoe UI Semibold", 9F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnExportarCuposExcel.ForeColor = System.Drawing.Color.White;
            this.btnExportarCuposExcel.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnExportarCuposExcel.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnExportarCuposExcel.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnExportarCuposExcel.IconMarginLeft = 11;
            this.btnExportarCuposExcel.IconPadding = 10;
            this.btnExportarCuposExcel.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnExportarCuposExcel.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnExportarCuposExcel.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnExportarCuposExcel.IconSize = 25;
            this.btnExportarCuposExcel.IdleBorderColor = System.Drawing.Color.Green;
            this.btnExportarCuposExcel.IdleBorderRadius = 40;
            this.btnExportarCuposExcel.IdleBorderThickness = 2;
            this.btnExportarCuposExcel.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(22)))), ((int)(((byte)(23)))), ((int)(((byte)(27)))));
            this.btnExportarCuposExcel.IdleIconLeftImage = ((System.Drawing.Image)(resources.GetObject("btnExportarCuposExcel.IdleIconLeftImage")));
            this.btnExportarCuposExcel.IdleIconRightImage = null;
            this.btnExportarCuposExcel.IndicateFocus = false;
            this.btnExportarCuposExcel.Location = new System.Drawing.Point(598, 45);
            this.btnExportarCuposExcel.Margin = new System.Windows.Forms.Padding(3, 3, 3, 10);
            this.btnExportarCuposExcel.Name = "btnExportarCuposExcel";
            this.btnExportarCuposExcel.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnExportarCuposExcel.OnDisabledState.BorderRadius = 40;
            this.btnExportarCuposExcel.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnExportarCuposExcel.OnDisabledState.BorderThickness = 2;
            this.btnExportarCuposExcel.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnExportarCuposExcel.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnExportarCuposExcel.OnDisabledState.IconLeftImage = null;
            this.btnExportarCuposExcel.OnDisabledState.IconRightImage = null;
            this.btnExportarCuposExcel.onHoverState.BorderColor = System.Drawing.Color.Green;
            this.btnExportarCuposExcel.onHoverState.BorderRadius = 40;
            this.btnExportarCuposExcel.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnExportarCuposExcel.onHoverState.BorderThickness = 2;
            this.btnExportarCuposExcel.onHoverState.FillColor = System.Drawing.Color.Green;
            this.btnExportarCuposExcel.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnExportarCuposExcel.onHoverState.IconLeftImage = null;
            this.btnExportarCuposExcel.onHoverState.IconRightImage = null;
            this.btnExportarCuposExcel.OnIdleState.BorderColor = System.Drawing.Color.Green;
            this.btnExportarCuposExcel.OnIdleState.BorderRadius = 40;
            this.btnExportarCuposExcel.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnExportarCuposExcel.OnIdleState.BorderThickness = 2;
            this.btnExportarCuposExcel.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(22)))), ((int)(((byte)(23)))), ((int)(((byte)(27)))));
            this.btnExportarCuposExcel.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnExportarCuposExcel.OnIdleState.IconLeftImage = ((System.Drawing.Image)(resources.GetObject("btnExportarCuposExcel.OnIdleState.IconLeftImage")));
            this.btnExportarCuposExcel.OnIdleState.IconRightImage = null;
            this.btnExportarCuposExcel.OnPressedState.BorderColor = System.Drawing.Color.Green;
            this.btnExportarCuposExcel.OnPressedState.BorderRadius = 40;
            this.btnExportarCuposExcel.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnExportarCuposExcel.OnPressedState.BorderThickness = 2;
            this.btnExportarCuposExcel.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(22)))), ((int)(((byte)(23)))), ((int)(((byte)(27)))));
            this.btnExportarCuposExcel.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnExportarCuposExcel.OnPressedState.IconLeftImage = null;
            this.btnExportarCuposExcel.OnPressedState.IconRightImage = null;
            this.btnExportarCuposExcel.Size = new System.Drawing.Size(137, 47);
            this.btnExportarCuposExcel.TabIndex = 165;
            this.btnExportarCuposExcel.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnExportarCuposExcel.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnExportarCuposExcel.TextMarginLeft = 0;
            this.btnExportarCuposExcel.TextPadding = new System.Windows.Forms.Padding(0, 0, 5, 0);
            this.btnExportarCuposExcel.UseDefaultRadiusAndThickness = true;
            this.btnExportarCuposExcel.Click += new System.EventHandler(this.btnExportarCuposExcel_Click);
            // 
            // btnExportarCapacidadesPDF
            // 
            this.btnExportarCapacidadesPDF.AllowAnimations = true;
            this.btnExportarCapacidadesPDF.AllowMouseEffects = true;
            this.btnExportarCapacidadesPDF.AllowToggling = false;
            this.btnExportarCapacidadesPDF.Anchor = System.Windows.Forms.AnchorStyles.Left;
            this.btnExportarCapacidadesPDF.AnimationSpeed = 200;
            this.btnExportarCapacidadesPDF.AutoGenerateColors = false;
            this.btnExportarCapacidadesPDF.AutoRoundBorders = false;
            this.btnExportarCapacidadesPDF.AutoSizeLeftIcon = true;
            this.btnExportarCapacidadesPDF.AutoSizeRightIcon = true;
            this.btnExportarCapacidadesPDF.BackColor = System.Drawing.Color.Transparent;
            this.btnExportarCapacidadesPDF.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(22)))), ((int)(((byte)(23)))), ((int)(((byte)(27)))));
            this.btnExportarCapacidadesPDF.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnExportarCapacidadesPDF.BackgroundImage")));
            this.btnExportarCapacidadesPDF.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnExportarCapacidadesPDF.ButtonText = " Exportar a PDF";
            this.btnExportarCapacidadesPDF.ButtonTextMarginLeft = 0;
            this.btnExportarCapacidadesPDF.ColorContrastOnClick = 45;
            this.btnExportarCapacidadesPDF.ColorContrastOnHover = 45;
            this.btnExportarCapacidadesPDF.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges6.BottomLeft = true;
            borderEdges6.BottomRight = true;
            borderEdges6.TopLeft = true;
            borderEdges6.TopRight = true;
            this.btnExportarCapacidadesPDF.CustomizableEdges = borderEdges6;
            this.btnExportarCapacidadesPDF.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnExportarCapacidadesPDF.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnExportarCapacidadesPDF.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnExportarCapacidadesPDF.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnExportarCapacidadesPDF.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnExportarCapacidadesPDF.Font = new System.Drawing.Font("Segoe UI Semibold", 9F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.btnExportarCapacidadesPDF.ForeColor = System.Drawing.Color.White;
            this.btnExportarCapacidadesPDF.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnExportarCapacidadesPDF.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnExportarCapacidadesPDF.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnExportarCapacidadesPDF.IconMarginLeft = 11;
            this.btnExportarCapacidadesPDF.IconPadding = 10;
            this.btnExportarCapacidadesPDF.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnExportarCapacidadesPDF.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnExportarCapacidadesPDF.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnExportarCapacidadesPDF.IconSize = 25;
            this.btnExportarCapacidadesPDF.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(231)))), ((int)(((byte)(76)))), ((int)(((byte)(80)))));
            this.btnExportarCapacidadesPDF.IdleBorderRadius = 40;
            this.btnExportarCapacidadesPDF.IdleBorderThickness = 2;
            this.btnExportarCapacidadesPDF.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(22)))), ((int)(((byte)(23)))), ((int)(((byte)(27)))));
            this.btnExportarCapacidadesPDF.IdleIconLeftImage = ((System.Drawing.Image)(resources.GetObject("btnExportarCapacidadesPDF.IdleIconLeftImage")));
            this.btnExportarCapacidadesPDF.IdleIconRightImage = null;
            this.btnExportarCapacidadesPDF.IndicateFocus = false;
            this.btnExportarCapacidadesPDF.Location = new System.Drawing.Point(172, 45);
            this.btnExportarCapacidadesPDF.Margin = new System.Windows.Forms.Padding(3, 3, 3, 10);
            this.btnExportarCapacidadesPDF.Name = "btnExportarCapacidadesPDF";
            this.btnExportarCapacidadesPDF.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnExportarCapacidadesPDF.OnDisabledState.BorderRadius = 40;
            this.btnExportarCapacidadesPDF.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnExportarCapacidadesPDF.OnDisabledState.BorderThickness = 2;
            this.btnExportarCapacidadesPDF.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnExportarCapacidadesPDF.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnExportarCapacidadesPDF.OnDisabledState.IconLeftImage = null;
            this.btnExportarCapacidadesPDF.OnDisabledState.IconRightImage = null;
            this.btnExportarCapacidadesPDF.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(231)))), ((int)(((byte)(76)))), ((int)(((byte)(80)))));
            this.btnExportarCapacidadesPDF.onHoverState.BorderRadius = 40;
            this.btnExportarCapacidadesPDF.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnExportarCapacidadesPDF.onHoverState.BorderThickness = 2;
            this.btnExportarCapacidadesPDF.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(231)))), ((int)(((byte)(76)))), ((int)(((byte)(80)))));
            this.btnExportarCapacidadesPDF.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnExportarCapacidadesPDF.onHoverState.IconLeftImage = null;
            this.btnExportarCapacidadesPDF.onHoverState.IconRightImage = null;
            this.btnExportarCapacidadesPDF.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(231)))), ((int)(((byte)(76)))), ((int)(((byte)(80)))));
            this.btnExportarCapacidadesPDF.OnIdleState.BorderRadius = 40;
            this.btnExportarCapacidadesPDF.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnExportarCapacidadesPDF.OnIdleState.BorderThickness = 2;
            this.btnExportarCapacidadesPDF.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(22)))), ((int)(((byte)(23)))), ((int)(((byte)(27)))));
            this.btnExportarCapacidadesPDF.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnExportarCapacidadesPDF.OnIdleState.IconLeftImage = ((System.Drawing.Image)(resources.GetObject("btnExportarCapacidadesPDF.OnIdleState.IconLeftImage")));
            this.btnExportarCapacidadesPDF.OnIdleState.IconRightImage = null;
            this.btnExportarCapacidadesPDF.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(231)))), ((int)(((byte)(76)))), ((int)(((byte)(80)))));
            this.btnExportarCapacidadesPDF.OnPressedState.BorderRadius = 40;
            this.btnExportarCapacidadesPDF.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnExportarCapacidadesPDF.OnPressedState.BorderThickness = 2;
            this.btnExportarCapacidadesPDF.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(22)))), ((int)(((byte)(23)))), ((int)(((byte)(27)))));
            this.btnExportarCapacidadesPDF.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnExportarCapacidadesPDF.OnPressedState.IconLeftImage = null;
            this.btnExportarCapacidadesPDF.OnPressedState.IconRightImage = null;
            this.btnExportarCapacidadesPDF.Size = new System.Drawing.Size(134, 47);
            this.btnExportarCapacidadesPDF.TabIndex = 168;
            this.btnExportarCapacidadesPDF.TextAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnExportarCapacidadesPDF.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnExportarCapacidadesPDF.TextMarginLeft = 0;
            this.btnExportarCapacidadesPDF.TextPadding = new System.Windows.Forms.Padding(0, 0, 5, 0);
            this.btnExportarCapacidadesPDF.UseDefaultRadiusAndThickness = true;
            this.btnExportarCapacidadesPDF.Click += new System.EventHandler(this.btnExportarCapacidadesPDF_Click);
            // 
            // frmCapacidadesYCupos
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(22)))), ((int)(((byte)(23)))), ((int)(((byte)(27)))));
            this.ClientSize = new System.Drawing.Size(937, 543);
            this.Controls.Add(this.tableLayoutPanel1);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            this.Icon = ((System.Drawing.Icon)(resources.GetObject("$this.Icon")));
            this.Name = "frmCapacidadesYCupos";
            this.Text = "frmCapacidadesYCupos";
            this.Load += new System.EventHandler(this.frmCapacidadesYCupos_Load);
            ((System.ComponentModel.ISupportInitialize)(this.dgvCapacidades)).EndInit();
            this.tableLayoutPanel1.ResumeLayout(false);
            this.tableLayoutPanel1.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.dgvCupos)).EndInit();
            this.ResumeLayout(false);

        }

        #endregion

        public System.Windows.Forms.DataGridView dgvCapacidades;
        private System.Windows.Forms.TableLayoutPanel tableLayoutPanel1;
        public System.Windows.Forms.DataGridView dgvCupos;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnBuscarCapacidad;
        private Bunifu.UI.WinForms.BunifuDatePicker dtpFechaCapacidades;
        private Bunifu.UI.WinForms.BunifuDatePicker dtpFechaCupos;
        private System.Windows.Forms.Label lblCapacidades;
        private System.Windows.Forms.Label lblCupos;
        private Bunifu.UI.WinForms.BunifuDropdown cbServicio;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnExportarCapacidadesPDF;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnExportarCapacidadesExcel;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnExportarCuposExcel;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnExportarCuposPDF;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnBuscarCupos;
    }
}